
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "7080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${MARIADB_USER:-app}
      PMA_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
    depends_on:
      - database
###< doctrine/doctrine-bundle ###
